#lang racket/base
;; deck IR -> a Rhombus program that draws it.
;;
;; The generated program imports glide-pptx/runtime.rhm, which is Rhombus naming
;; over the same Racket runtime the Racket back end uses, so both outputs draw
;; identically and a fidelity fix lands in both at once.
;;
;; Rhombus is the more interesting target for where this is headed: its pict
;; library has animation built in, which is the part of a deck that PowerPoint
;; cannot express and code can.
(require racket/list racket/string racket/format racket/path racket/file
         "ir.rkt" "emit-common.rkt")
(provide rhombus-flavor emit-rhombus-deck write-rhombus-deck)

(define LINE-WIDTH 88)

;; Canonical names are kebab-cased; Rhombus spells them with underscores.
(define (map-name n)
  (regexp-replace* #rx"-" n "_"))

;; Rhombus cannot spell a keyword ending in `?`, so the shim drops it.
(define (keyword-name kw)
  (regexp-replace* #rx"-" (regexp-replace #rx"[?]$" kw "") "_"))

(define (render-value v fl)
  (cond
    [(v:num? v) (num-string (v:num-x v))]
    [(v:str? v) (format "~s" (v:str-s v))]
    [(v:sym? v) (format "#'~a" (v:sym-s v))]
    [(v:bool? v) (if (v:bool-b v) "#true" "#false")]
    [(v:raw? v) (v:raw-s v)]
    [(v:list? v)
     (format "[~a]" (string-join (for/list ([i (in-list (v:list-items v))]) (render i fl)) ", "))]
    [(v:pair? v) (format "pair(~a, ~a)" (render (v:pair-a v) fl) (render (v:pair-b v) fl))]
    [else (format "~a" v)]))

(define rhombus-flavor
  (flavor 'rhombus map-name render-value
          (lambda (name) (string-append name "("))
          ")" "" ", " ", "
          (lambda (kw) (format "~~~a: " (keyword-name kw)))
          "// "))

;; ------------------------------------------------------------------- program

(define (line out ind fmt . args)
  (write-string (make-string (max 0 ind) #\space) out)
  (write-string (apply format fmt args) out)
  (newline out))

(define (write-element out ind e last?)
  (unless (string=? "" (element-name e))
    (line out ind "// ~a (id ~a)" (element-name e) (element-id e)))
  (define ls (render-lines (element->value e) rhombus-flavor ind LINE-WIDTH))
  (for ([l (in-list ls)] [i (in-naturals)])
    (write-string l out)
    ;; Arguments of the enclosing slide_canvas call are comma-separated.
    (when (and (= i (sub1 (length ls))) (not last?)) (write-string "," out))
    (newline out)))

(define (emit-rhombus-deck d out
                           #:source-name [source-name #f]
                           #:media-subdir [media-subdir "media"]
                           #:media-names [media-names (hash)]
                           #:pdf-name [pdf-name "slides.pdf"])
  (parameterize ([current-media-names media-names]
                 [current-deck-font (dominant-font d)])
    (line out 0 "#lang rhombus/and_meta")
    (line out 0 "// Generated by glide-pptx from ~a." (or source-name (deck-source d)))
    (line out 0 "// ~a slides at ~a x ~a pt."
          (length (deck-slides d)) (num-string (deck-width d)) (num-string (deck-height d)))
    (line out 0 "//")
    (line out 0 "// Every slide_N is a pict. PowerPoint supplied the positions; from here")
    (line out 0 "// on it is code, and nothing rewrites this file unless you ask it to.")
    (newline out)
    (line out 0 "import:")
    (line out 2 "lib(\"glide-pptx/runtime.rhm\") open")
    (newline out)
    ;; Exported so the deck can be composed from another module, and so
    ;; `raco glide-pptx export` can find the slides.
    (line out 0 "export:")
    (line out 2 "slide_width")
    (line out 2 "slide_height")
    (line out 2 "all_slides")
    (for ([s (in-list (deck-slides d))])
      (line out 2 "slide_~a" (slide-index s)))
    (newline out)
    (line out 0 "def slide_width = ~a" (num-string (deck-width d)))
    (line out 0 "def slide_height = ~a" (num-string (deck-height d)))
    (newline out)
    (line out 0 "// The theme font. Runs that name no typeface use this one, so restyling")
    (line out 0 "// the whole deck is one edit.")
    (line out 0 "current_default_font(~s)" (current-deck-font))
    (unless (zero? (hash-count media-names))
      (newline out)
      (line out 0 "// Images sit next to this file, so the program travels as a folder.")
      (line out 0 "def media = media_lookup(~s)" media-subdir))
    (for ([s (in-list (deck-slides d))])
      (newline out)
      (line out 0 "// ~a" (make-string (- LINE-WIDTH 3) #\-))
      (line out 0 "// Slide ~a~a" (slide-index s)
            (if (equal? (slide-name s) (format "Slide ~a" (slide-index s)))
                "" (format ": ~a" (slide-name s))))
      (line out 0 "def slide_~a = slide_canvas(" (slide-index s))
      (define elements (append (slide-inherited s) (slide-elements s)))
      (line out 2 "~a"
            (format "~~width: slide_width, ~~height: slide_height,"))
      (line out 2 "~~background: ~a~a"
            (render (slide-background-value s) rhombus-flavor)
            (if (null? elements) "" ","))
      (define n (length (slide-inherited s)))
      (for ([e (in-list elements)] [i (in-naturals)])
        (when (and (positive? n) (= i 0))
          (line out 2 "// Drawn by the slide layout and master, not by this slide."))
        (when (and (positive? n) (= i n))
          (line out 2 "// The slide's own shapes."))
        (write-element out 2 e (= i (sub1 (length elements)))))
      (line out 0 ")"))
    (newline out)
    (line out 0 "def all_slides = [~a]"
          (string-join (for/list ([s (in-list (deck-slides d))])
                         (format "slide_~a" (slide-index s)))
                       ", "))
    (newline out)
    (line out 0 "module main:")
    (line out 2 "deck_to_pdf(all_slides, ~s, ~~width: slide_width, ~~height: slide_height)"
          pdf-name)
    (line out 2 "println(\"wrote \" +& ~s)" pdf-name)))

(define (write-rhombus-deck d path
                            #:source-name [source-name #f]
                            #:media-subdir [media-subdir "media"]
                            #:pdf-name [pdf-name #f])
  (define names (copy-media! d path media-subdir))
  (call-with-output-file path #:exists 'replace
    (lambda (out)
      (emit-rhombus-deck d out
                         #:source-name source-name
                         #:media-subdir media-subdir
                         #:media-names names
                         #:pdf-name (or pdf-name (default-pdf-name path)))))
  path)
