#lang racket/base
;; deck IR -> a Racket program that draws it.
;;
;; Only the Racket surface syntax and the program's frame live here; deciding
;; what to emit is shared with the Rhombus back end in emit-common.
(require racket/list racket/string racket/format racket/path racket/file
         "ir.rkt" "emit-common.rkt")
(provide racket-flavor emit-racket-deck write-racket-deck)

(define LINE-WIDTH 88)

(define (map-name n)
  ;; The Racket runtime spells the text constructors with a star, to keep them
  ;; from colliding with `pict`'s own `text`.
  (case n
    [("run") "run*"] [("para") "para*"] [("body") "body*"]
    [else n]))

(define (render-value v fl)
  (cond
    [(v:num? v) (num-string (v:num-x v))]
    [(v:str? v) (format "~s" (v:str-s v))]
    [(v:sym? v) (format "'~a" (v:sym-s v))]
    [(v:bool? v) (if (v:bool-b v) "#t" "#f")]
    [(v:raw? v) (v:raw-s v)]
    [(v:list? v)
     (format "(list ~a)" (string-join (for/list ([i (in-list (v:list-items v))])
                                        (render i fl)) " "))]
    [(v:pair? v) (format "(cons ~a ~a)" (render (v:pair-a v) fl) (render (v:pair-b v) fl))]
    [else (format "~a" v)]))

(define racket-flavor
  (flavor 'racket map-name render-value
          (lambda (name) (string-append "(" name))
          ")" " " " " " "
          (lambda (kw) (format "#:~a " kw))
          ";; "))

;; ------------------------------------------------------------------- program

(define (line out ind fmt . args)
  (write-string (make-string (max 0 ind) #\space) out)
  (write-string (apply format fmt args) out)
  (newline out))

(define (write-element out ind e)
  (unless (string=? "" (element-name e))
    (line out ind ";; ~a (id ~a)" (element-name e) (element-id e)))
  (for ([l (in-list (render-lines (element->value e) racket-flavor ind LINE-WIDTH))])
    (write-string l out)
    (newline out)))

(define (emit-racket-deck d out
                          #:source-name [source-name #f]
                          #:media-subdir [media-subdir "media"]
                          #:media-names [media-names (hash)]
                          #:pdf-name [pdf-name "slides.pdf"])
  (parameterize ([current-media-names media-names]
                 [current-deck-font (dominant-font d)])
    (line out 0 "#lang racket/base")
    (line out 0 ";; Generated by glide-pptx from ~a." (or source-name (deck-source d)))
    (line out 0 ";; ~a slides at ~a x ~a pt."
          (length (deck-slides d)) (num-string (deck-width d)) (num-string (deck-height d)))
    (line out 0 ";;")
    (line out 0 ";; This is ordinary Racket: every slide-N is a pict, so it composes with")
    (line out 0 ";; anything in `pict`. PowerPoint supplied the positions; from here on it")
    (line out 0 ";; is code, and nothing rewrites this file unless you ask it to.")
    (newline out)
    (line out 0 "(require pict glide-pptx/runtime)")
    (newline out)
    ;; Provided so the deck can be composed from another module, and so
    ;; `raco glide-pptx export` can find the slides.
    (line out 0 "(provide slide-width slide-height all-slides~a)"
          (apply string-append
                 (for/list ([s (in-list (deck-slides d))])
                   (format "\n         slide-~a" (slide-index s)))))
    (newline out)
    (line out 0 "(define slide-width ~a)" (num-string (deck-width d)))
    (line out 0 "(define slide-height ~a)" (num-string (deck-height d)))
    (newline out)
    (line out 0 ";; The theme font. Runs that name no typeface use this one, so restyling")
    (line out 0 ";; the whole deck is one edit.")
    (line out 0 "(current-default-font ~s)" (current-deck-font))
    (unless (zero? (hash-count media-names))
      (newline out)
      (line out 0 ";; Images sit next to this file, so the program travels as a folder.")
      (line out 0 "(define media (media-lookup ~s))" media-subdir))
    (for ([s (in-list (deck-slides d))])
      (newline out)
      (line out 0 ";; ~a" (make-string (- LINE-WIDTH 3) #\-))
      (line out 0 ";; Slide ~a~a" (slide-index s)
            (if (equal? (slide-name s) (format "Slide ~a" (slide-index s)))
                "" (format ": ~a" (slide-name s))))
      (line out 0 "(define slide-~a" (slide-index s))
      (line out 2 "(slide-canvas")
      (line out 3 "#:width slide-width #:height slide-height")
      (line out 3 "#:background ~a" (render (slide-background-value s) racket-flavor))
      (unless (null? (slide-inherited s))
        (newline out)
        (line out 3 ";; Drawn by the slide layout and master, not by this slide.")
        (for ([e (in-list (slide-inherited s))]) (write-element out 3 e))
        (newline out)
        (line out 3 ";; The slide's own shapes."))
      (for ([e (in-list (slide-elements s))]) (write-element out 3 e))
      (line out 2 "))"))
    (newline out)
    (line out 0 "(define all-slides")
    (line out 2 "(list ~a))"
          (string-join (for/list ([s (in-list (deck-slides d))])
                         (format "slide-~a" (slide-index s)))
                       " "))
    (newline out)
    (line out 0 "(module+ main")
    (line out 2 "(deck->pdf all-slides ~s #:width slide-width #:height slide-height)" pdf-name)
    (line out 2 "(printf \"wrote ~~a\\n\" ~s))" pdf-name)))

(define (write-racket-deck d path
                          #:source-name [source-name #f]
                          #:media-subdir [media-subdir "media"]
                          #:pdf-name [pdf-name #f])
  (define names (copy-media! d path media-subdir))
  (call-with-output-file path #:exists 'replace
    (lambda (out)
      (emit-racket-deck d out
                        #:source-name source-name
                        #:media-subdir media-subdir
                        #:media-names names
                        #:pdf-name (or pdf-name (default-pdf-name path)))))
  path)
